load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "utils",
    hdrs = [
        "gen_string.h",
        "gen_data_stream.h"
    ],
    visibility = ["//:__pkg__","//theta_dup:__pkg__","//test:__pkg__"],
)
